export const MESSAGE_SPACING = 5;
export const NUMBER_OF_TRACK = 4;
export const TRACK_LENGTH = 10;

export const SECTION_RESOLUTION = {
    _3x4: "3x4",
}

export const LAYOUTS = [
    [
        SECTION_RESOLUTION._3x4, SECTION_RESOLUTION._3x4, SECTION_RESOLUTION._3x4, SECTION_RESOLUTION._3x4, SECTION_RESOLUTION._3x4
    ],
]
