export const SECTION_RESOLUTION = {
    _4x3: "4x3",
}

export const LAYOUTS = [
    [
        SECTION_RESOLUTION._4x3, SECTION_RESOLUTION._4x3, SECTION_RESOLUTION._4x3, SECTION_RESOLUTION._4x3, SECTION_RESOLUTION._4x3
    ],
]
